name: smart_device_dart
description: Controlling CyBear Jinni Smart Devices
version: 1.0.1
homepage: https://github.com/CyBear-Jinni/CBJ_Smart-Device
author: Guy Luz

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # Functional programming thingies, let you use multiple return types
  dartz: ^0.9.2
  # Convert enum to string
  enum_to_string: ^2.0.1
  # Convenient code generator for get_it
  #  injectable: ^0.4.0+1 # Does not work on my armhf32, can be lack of ram https://TypeAdaptergithub.com/dart-lang/pub/issues/2347
  # Allow returning more than one type of object
  equatable: ^2.0.2
  # Firebase Auth and Firestore SDKs.
  firedart: ^0.9.0+1
  # For the injection, allow accessing an object from anywhere in an App
  get_it: ^7.1.3
  # Key-value database
  hive: ^2.0.4
  # Checks for an internet connection by opening a socket
  internet_connection_checker: ^0.0.1+1
  # Collection of lint rules for Dart and Flutter projects
  lint: ^1.5.3
  # Process run helpers for Linux/Win/Mac.
  process_run: ^0.12.1
  # Provides parse, inspect, and manipulate stack traces
  stack_trace: ^1.10.0
  uuid: ^3.0.4


dev_dependencies:
  # A generator for injectable library
  #  injectable_generator: ^0.4.0 # Does not work on my armhf32, can be lack of ram https://github.com/dart-lang/pub/issues/2347
  build_runner:
  hive_generator: ^1.1.0
  # Library for mocks
  mockito: ^5.0.10
  test: ^1.17.7


