name: Dart CI

on:
  push:
    branches: [ master , dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      working-directory: cbj_smart-device
      run: pub get
    - name: Run tests
      working-directory: cbj_smart-device
      run: pub run test
